translated "A GIF decoder: an exercise in Go interfaces"
ymotongpoo/goblog-ja pull request #4
Opened 2017-07-22 11:29 UTC by cia-rana

[A GIF decoder: an exercise in Go interfaces](https://blog.golang.org/gif-decoder-exercise-in-go-interfaces) を日本語訳しました。  
翻訳に加えて、必要な画像データのためのディレクトリを作成し、そこに画像データを入れています。

2017-07-27 14:55 UTC, ymotongpoo requested changes
素晴らしい日本語訳をありがとうございます。細かい部分のコメントをしましたが、とても自然でした。これからもよろしくお願いします！

2017-07-27 14:55 UTC, ymotongpoo commented on content/post/gif-decoder-exercise-in-go-interfaces.md
> +GIFのピクセルデータをGoでデコードするために、私たちは `compress/lzw` パッケージからLZWデコンプレッサを使うことができます。そのパッケージには、[ドキュメント](http://golang.org/pkg/compress/lzw/#NewReader)曰く、「rから読み出したデータを解凍することによって読み出し可能となる」オブジェクトを返すNewReader関数があります
nit suggestion: 「私たち」は省略したほうが自然になると思いますがどうでしょうか。

2017-07-27 14:55 UTC, ymotongpoo commented on content/post/gif-decoder-exercise-in-go-interfaces.md
> +しかし私たちは、`NewReader` の最初の引数として入力ファイルを与えることはできません。それはデコンプレッサがバイトストリームを要求しているにも関わらずGIFデータはアンパックが必要なブロックストリームになっているからです。この問題を扱うために、私たちはそれをデブロッキングするためのちょっとしたコードにより入力 `io.Reader` をラップすることができます。さらにそのコードを再び
ditto

2017-07-27 14:55 UTC, ymotongpoo commented on content/post/gif-decoder-exercise-in-go-interfaces.md
> +2-4行目はちょうどサニティーチェック（異常がないかの確認）に当たります: データを置くところがなければ0を返す。起こり得ないですが、念のためです。
コロンに関しては以前の指摘と同様に日本語に置き換えた方が良いと思います。
http://www.eigo-nikki.com/article/13213998.html

また「です・ます」調と「だ・である」調は文章全体で統一したほうが良いです。今回の場合は「0を返す」でなく、「0を返します」になります。

2017-07-27 14:55 UTC, ymotongpoo commented on content/post/gif-decoder-exercise-in-go-interfaces.md
> +`blockReader` 型が与えられると、私たちは画像データストリームを入力リーダーをラップすることによりアンパックできます。ファイルについてはこのようになります:
ditto:「私たち」

2017-07-27 14:55 UTC, ymotongpoo commented on content/post/gif-decoder-exercise-in-go-interfaces.md
> +`NewReader` 呼び出しをちょうど `blockReader` を `NewReader` 呼び出しの中で組み立てたように、`ReadFull` の引数リストに置くことで私たちは一時変数 `lzwr` を避けることができますが、1行のコードに詰め過ぎかもしれません。
ditto:「私たち」

2017-07-27 16:17 UTC, cia-rana commented
レビューしていただきありがとうございます。そう言っていただけて光栄です！

さて、指摘していただいたところはまとめて修正しました。
「私たち」の部分は原文と意味がずれない程度に省きたいと思います。

あとは、原文中の"We stitch them together with this thunderclap, straight from the code:"の部分の訳が少し自信なかったのですが、ニュアンスは伝わっているでしょうか？

2017-07-30 05:25 UTC, ymotongpoo requested changes
ありがとうございます。その部分は確かに違和感があるので、コメントをしました。

2017-07-30 05:25 UTC, ymotongpoo commented on content/post/gif-decoder-exercise-in-go-interfaces.md
> +`blockReader` の実装とライブラリから利用可能なLZWコンプレッサにより、画像データストリームをデコードするために必要なピースが全て揃いました。私たちはコードから真っ直ぐに伸びたこの衝撃ともにそれら紡ぎ合わせます:
"straight from"は「単刀直入に」というようなニュアンスです。

"this thunderclap"は、その次のコードで示されているような驚くべき短さであっという間に、というようなニュアンスです。

2017-07-30 15:52 UTC, cia-rana commented
1文をまとめて「コードを短く素直に繋ぎ合わせる」というニュアンスに変えました。

2019-10-06 02:05 UTC, merged